title: donghyeong.log
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: hong85dong@gmail.com
github_username: dh0508
twitter_username: twitter
instagram_username: donghyeong_0805
linkedin_username: linkedin
facebook_username: facebook


# External API
giscus_repo: "dh0508/dh0508.github.io"
giscus_repoId: "R_kgDOPLYwQA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOPLYwQM4Cs3N8"
goatcounter_code: dh0508
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
